// Generated by CoffeeScript 1.8.0
(function() {
  window.onload = function() {
    var TEX_SCALE, UNIT, bodyHeight, bodyWidth, lastFrame, loader, playerSprite, processInput, render, renderer, stage, step, stillRendering, update;
    stage = new PIXI.Stage(0xffffff);
    renderer = PIXI.autoDetectRenderer(bodyWidth = Math.max(document.documentElement['clientWidth'], document.body['scrollWidth'], document.documentElement['scrollWidth'], document.body['offsetWidth'], document.documentElement['offsetWidth']), bodyHeight = Math.max(document.documentElement['clientHeight'], document.body['scrollHeight'], document.documentElement['scrollHeight'], document.body['offsetHeight'], document.documentElement['offsetHeight']));
    UNIT = bodyWidth / 100.0;
    TEX_SCALE = UNIT / 82.0;
    loader = new PIXI.AssetLoader(['img/animalTex.png']);
    document.body.appendChild(renderer.view);
    stillRendering = false;
    lastFrame = -1;
    playerSprite = PIXI.Sprite.fromImage('img/animalTex.png');
    playerSprite.tint = 0xcccccc;
    playerSprite.scale = new PIXI.Point(TEX_SCALE, TEX_SCALE);
    stage.addChild(playerSprite);
    processInput = function() {};
    update = function() {};
    render = function() {
      if (!stillRendering) {
        stillRendering = true;
        renderer.render(stage);
        return stillRendering = false;
      }
    };
    step = function() {
      requestAnimFrame(step);
      processInput();
      update();
      return render();
    };
    loader.onComplete = function() {
      return step();
    };
    return loader.load();
  };

}).call(this);
