// Generated by CoffeeScript 1.8.0
(function() {
  this.MathUtil = (function() {
    function MathUtil() {}

    MathUtil.randInt = function(min, max) {
      return max - (max - min) * (1 - Math.random());
    };

    return MathUtil;

  })();

}).call(this);
