// Generated by CoffeeScript 1.8.0
(function() {
  var MathUtil;

  MathUtil = (function() {
    function MathUtil() {}

    MathUtil.randInt = function(min, max) {
      return (Math.random() * (max - min + 1) + min) | 0;
    };

    return MathUtil;

  })();

}).call(this);
