// Generated by CoffeeScript 1.8.0
(function() {
  this.MathUtil = (function() {
    function MathUtil() {}

    MathUtil.randInt = function(min, max) {
      return Math.random() * (max - min) + min;
    };

    return MathUtil;

  })();

}).call(this);
