// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.AnimalController = (function() {
    function AnimalController(model) {
      this.model = model;
      this.think = __bind(this.think, this);
      this.direction = new Vector(0.0, 0.0);
    }

    AnimalController.prototype.think = function() {
      var len;
      len = this.direction.x * this.direction.x + this.direction.y * this.direction.y;
      if (len > 1) {
        this.direction.x /= len;
        this.direction.y /= len;
        return len = 1;
      }
    };

    return AnimalController;

  })();

}).call(this);
