// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.AnimalController = (function() {
    function AnimalController(model) {
      this.model = model;
      this.think = __bind(this.think, this);
      this.direction = new Vector(0.0, 0.0);
    }

    AnimalController.prototype.think = function(dt) {
      var dir, len;
      len = this.direction.length();
      dir = this.direction.clone();
      if (len > 1.0) {
        dir.normalize();
        len = 1.0;
      }
      this.model.acceleration.set(dir.mul(this.model.maxAcc));
      if (dir.x === 0) {
        this.model.acceleration.x = -Constants.STOP_FORCE * this.model.velocity.x / dt;
      }
      if (dir.y === 0) {
        return this.model.acceleration.y = -Constants.STOP_FORCE * this.model.velocity.y / dt;
      }
    };

    return AnimalController;

  })();

}).call(this);
