// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.AnimalController = (function() {
    function AnimalController(model) {
      this.model = model;
      this.think = __bind(this.think, this);
      this.direction = new Vector(0.0, 0.0);
    }

    AnimalController.prototype.think = function() {
      var len;
      len = this.direction.length();
      if (len > 1.0) {
        this.direction.normalize();
        len = 1.0;
      }
      this.model.acceleration = this.direction.mulCpy(this.model.maxAcc);
      return this.direction.set(0);
    };

    return AnimalController;

  })();

}).call(this);
