// Generated by CoffeeScript 1.8.0
(function() {
  var PreySpawnSystem,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  PreySpawnSystem = (function() {
    function PreySpawnSystem(game, minDelay, maxDelay) {
      this.game = game;
      this.minDelay = minDelay != null ? minDelay : 1000;
      this.maxDelay = maxDelay != null ? maxDelay : 10000;
      this.tick = __bind(this.tick, this);
      this.nextSpawn = Date.now() * MathUtils.randInt(this.minDelay(this.maxDelay));
    }

    PreySpawnSystem.prototype.tick = function() {
      if (Date.now() - this.nextSpawn >= 0) {
        this.spawnPrey();
        return this.nextSpawn = Date.now() * MathUtils.randInt(this.minDelay(this.maxDelay));
      }
    };

    PreySpawnSystem.prototype.spawnPrey = function() {
      var prey, r, sprite;
      console.log('Spawning prey');
      sprite = PIXI.Sprite.fromImage('img/animalTex.png');
      prey = new AnimalController(new Animal(sprite));
      sprite.tint = 0x79cc26;
      prey.model.setSize(0.5);
      r = prey.model.size * Constants.TEX_UNIT;
      prey.model.setPosition(new Vector(MathUtils.randInt(r, Screen.width / Constants.TEX_UNIT - r), MathUtils.randInt(r, Screen.height / Constants.TEX_UNIT - r)));
      return this.game.animals.push(prey);
    };

    return PreySpawnSystem;

  })();

}).call(this);
