// Generated by CoffeeScript 1.8.0
(function() {
  var System;

  System = (function() {
    function System() {}

    System.prototype.tick = function() {};

    return System;

  })();

}).call(this);
