// Generated by CoffeeScript 1.8.0
(function() {
  var Vector;

  module.exports = Vector = (function() {
    function Vector() {}

    Vector.prototype.contructor = function(x, y) {
      this.x = x != null ? x : 0;
      this.y = y != null ? y : 0;
    };

    return Vector;

  })();

}).call(this);
