// Generated by CoffeeScript 1.8.0
(function() {
  this.Vector = (function() {
    function Vector(x, y) {
      this.x = x != null ? x : 0;
      this.y = y != null ? y : 0;
    }

    return Vector;

  })();

}).call(this);
