// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Vector = (function() {
    function Vector(x, y) {
      this.x = x != null ? x : 0;
      this.y = y != null ? y : 0;
      this.length = __bind(this.length, this);
      this.set = __bind(this.set, this);
      this.clone = __bind(this.clone, this);
    }

    Vector.prototype.clone = function() {
      return new Vector(this.x, this.y);
    };

    Vector.prototype.set = function(x, y) {
      if (x == null) {
        x = 0;
      }
      this.x = x;
      return this.y = y != null ? y : x;
    };

    Vector.prototype.length = function() {
      return Math.sqrt(this.x * this.x + this.y * this.y);
    };

    return Vector;

  })();

}).call(this);
