// Generated by CoffeeScript 1.8.0
(function() {
  var Animal;

  Animal = (function() {
    function Animal(position, speed, turnSpeed, orientation) {
      this.position = position;
      this.speed = speed;
      this.turnSpeed = turnSpeed;
      this.orientation = orientation != null ? orientation : 0;
      this.attitude = 0;
    }

    return Animal;

  })();

}).call(this);
