// Generated by CoffeeScript 1.8.0
(function() {
  this.Constants = (function() {
    function Constants() {}

    Constants.UNIT = Screen.width / 100.0;

    Constants.TEX_RAD = 82.0;

    Constants.TEX_SCALE = UNIT / TEX_RAD;

    return Constants;

  })();

}).call(this);
