// Generated by CoffeeScript 1.8.0
(function() {
  this.Constants = (function() {
    function Constants() {}

    Constants.UNIT = Screen.width / 100.0;

    Constants.TEX_RAD = 41.0;

    Constants.TEX_UNIT = Constants.TEX_RAD / Constants.UNIT;

    Constants.TEX_SCALE = Constants.UNIT / Constants.TEX_RAD;

    Constants.STOP_FORCE = 0.1;

    return Constants;

  })();

}).call(this);
