// Generated by CoffeeScript 1.8.0
(function() {
  this.Screen = (function() {
    var bodyHeight, _ref, _ref1, _ref2, _ref3, _ref4;

    function Screen() {}

    Screen.width = Math.max(document.documentElement['clientWidth'], document.body['scrollWidth'], document.documentElement['scrollWidth'], document.body['offsetWidth'], document.documentElement['offsetWidth']);

    Screen.height = bodyHeight = Math.max((_ref = document.documentElement) != null ? _ref['clientHeight'] : void 0, (_ref1 = document.body) != null ? _ref1['scrollHeight'] : void 0, (_ref2 = document.documentElement) != null ? _ref2['scrollHeight'] : void 0, (_ref3 = document.body) != null ? _ref3['offsetHeight'] : void 0, (_ref4 = document.documentElement) != null ? _ref4['offsetHeight'] : void 0);

    return Screen;

  })();

}).call(this);
