// Generated by CoffeeScript 1.8.0
(function() {
  var Screen;

  Screen = (function() {
    var bodyHeight;

    function Screen() {}

    Screen.width = Math.max(document.documentElement['clientWidth'], document.body['scrollWidth'], document.documentElement['scrollWidth'], document.body['offsetWidth'], document.documentElement['offsetWidth']);

    Screen.height = bodyHeight = Math.max(document.documentElement['clientHeight'], document.body['scrollHeight'], document.documentElement['scrollHeight'], document.body['offsetHeight'], document.documentElement['offsetHeight']);

    return Screen;

  })();

}).call(this);
